<!-- Start Google Tag Manager -->
<?php
$gtmCode = Mage::getStoreConfig('google/ambimax_googletagmanager/gtm_code');
?>
<script type="text/javascript">// <![CDATA[
    (function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
            'gtm.start': new Date().getTime(), event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
            j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
            'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', '<?php echo $gtmCode; ?>'');
    // ]]></script>
<!-- End Google Tag Manager -->